credentials:
  usernames:
    qa_team:
      name: qa_team
      password: qa_team@123
    ml_team:
      name: ml_team
      password: ml_team@123
cookie:
  expiry_days: 30
  key: authentication_key
  name: authentication
preauthorized:
  emails:
    - tbalaji8822@gmail.com
